; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5stack-cardputer

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder
lib_ldf_mode = deep+

[env:m5stack-cardputer]
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 1500000
build_flags = 
	-I../include
	-DESP32S3
	;-DCORE_DEBUG_LEVEL=5
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DUSER_SETUP_LOADED=1
	-DST7789_DRIVER
	-DTFT_WIDTH=135
	-DTFT_HEIGHT=240
	-DCGRAM_OFFSET
	-DUSE_HSPI_PORT
	-DTFT_MOSI=35
	-DTFT_SCLK=36
	-DTFT_CS=37
	-DTFT_DC=34
	-DTFT_RST=33
	-DTFT_BL=38
	-DTFT_BACKLIGHT_ON=HIGH
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=20000000
	-DLOAD_GLCD
	-DLOAD_FONT2
	-DLOAD_FONT4
	-DLOAD_FONT6
	-DLOAD_FONT7
	-DLOAD_FONT8
	-DLOAD_GFXFF
	-DSMOOTH_FONT

lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	adafruit/Adafruit TCA8418@^1.0.2
